---
- hosts: local
  tasks:
    - name: Load optional configuration files
      ansible.builtin.include_vars:
        dir: /var/local/silverblue-config
        extensions: ['yml', 'yaml']
      failed_when: false
      tags: always

  roles:
    - role: system_setup
      tags:
        - system_setup
        - flatpak

    - role: system_update
      tags:
        - system_update
        - ostree

    - role: shell_config
      tags:
        - shell_config
        - aliases
        - bash

    - role: security
      tags:
        - security
        - firewall

    - role: go_setup
      tags:
        - go_setup
        - golang
        - go

    - role: update_routine
      tags:
        - update_routine
        - runner
        - desktop

    - role: ansible_pull
      tags:
        - ansible_pull
        - pull
