---
- name: Sicherstellen, dass firewalld aktiv und aktiviert ist
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Standard-Zone auf DROP setzen
  ansible.posix.firewalld:
    zone: public
    target: DROP
    state: present
    permanent: true

- name: Globale Ausnahmen aus firewall_allowed_ports erlauben
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ firewall_allowed_ports }}"

- name: App-spezifische Ports aus flatpak_apps erlauben (falls definiert)
  ansible.posix.firewalld:
    port: "{{ item.1 }}"
    zone: public
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ flatpak_apps | subelements('ports', skip_missing=True) }}"
