---
- name: Zusätzliche RPM-Pakete via rpm-ostree verwalten
  community.general.rpm_ostree_pkg:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    apply_live: true
  loop: "{{ rpm_ostree_packages }}"
  register: rpm_ostree_pkg
  until: rpm_ostree_pkg is not failed
  retries: 5
  delay: 10
