---
- name: Flathub Repository hinzufügen
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Flatpak-Pakete aus zentraler Liste verwalten
  community.general.flatpak:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
    method: user
    remote: "{{ item.repo | default('flathub') }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ flatpak_apps }}"

- name: Alle installierten Flatpaks aktualisieren
  community.general.flatpak:
    name: "*"
    state: latest
    method: user
