---
- name: Flathub Repository systemweit hinzufügen
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Flatpak-Pakete aus zentraler Liste systemweit verwalten
  community.general.flatpak:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
    method: system
    remote: "{{ item.repo | default('flathub') }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ flatpak_apps }}"

- name: Alle installierten systemweiten Flatpaks aktualisieren
  ansible.builtin.command:
    cmd: flatpak update --system --noninteractive
  changed_when: false
