---
- name: Prüfen, ob die Pull-Konfiguration in /var/local/silverblue-config existiert
  ansible.builtin.stat:
    path: /var/local/silverblue-config/pull_vars.yml
  register: pull_config_file

- name: Ansible-Repository lokal klonen, falls Konfiguration vorhanden
  when: pull_config_file.stat.exists
  block:
    - name: Variablen für das Setup laden
      ansible.builtin.include_vars:
        file: /var/local/silverblue-config/pull_vars.yml

    - name: Preflight - Prüfen, ob pull_repo_url definiert ist
      ansible.builtin.assert:
        that:
          - pull_repo_url is defined
          - pull_repo_url | length > 0
        fail_msg: "Die Variable 'pull_repo_url' ist in /var/local/silverblue-config/pull_vars.yml nicht definiert."

    - name: Preflight - Zielverzeichnis für das interne Repo vorbereiten
      ansible.builtin.file:
        path: /var/local/silverblue-internal-repo
        state: directory
        mode: '0700'

    - name: Repository lokal klonen oder aktualisieren
      ansible.builtin.git:
        repo: "https://{{ pull_token }}:@{{ pull_repo_url | regex_replace('^https://', '') }}"
        dest: /var/local/silverblue-internal-repo
        version: "{{ pull_repo_branch | default('main') }}"
        force: true
      register: repo_clone
